### ISSUE TITLE
Members should be able to edit their profile information

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#11]
In gitlab by @marcondag on Feb 19, 2018, 15:08

As a debt collective member I want to be able to edit my profile information so that if my information changes then my profile is in sync

## Tasks

- [ ] Change password by providing the current password
- [ ] Change any profile field
- [ ] Change profile picture
- [ ] Accessible only by user

## Assumptions

1. There is a way to upload and save profile pictures (#8)

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 19, 2018, 15:19

changed the description

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 16:16

added ~3522061 label

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 16:10

removed ~3521981 label

**Comment by marcondag** [comment]
In gitlab by @annlarson on Feb 23, 2018, 14:26

can we also make it possible for them to upload documents to their profile?

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 23, 2018, 15:11

Is the idea that they might re-use a document for multiple disputes?

**Comment by marcondag** [comment]
In gitlab by @annlarson on Feb 23, 2018, 15:13

yes - but also they will get letters back from the creditors answering the disputes and it might be nice for them to be able to archive those we can see them.

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 23, 2018, 15:19

Just thinking that it might make more sense to make the profile only
display the documents that members upload through the dispute process.
Otherwise people might just upload arbitrary documents and use us a
document store, which wouldn't really be desirable. For the letters they
receive back, we could make this a final optional step of the dispute
process, that way we automatically know which dispute the letter is a
response too, the admin gets notified in at least that way (if the
member doesn't follow up with an email on their own). And we can still
display this in the profile as needed.
