### ISSUE TITLE
Implement "Media Page"

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#138]
We have the media page designs https://www.figma.com/file/HM5nuixnJQD31TWqk4wE7ZNt/DS_Media-Page_designs

The idea is to implement a Jekyll based website integrated with Siteleaf, so admins can update and publish articles in the media page

## Acceptance

- [x] Implement media page as designs
- [ ] ~~Split member profiles into profiles (videos) and letters (Q/A)~~ (https://github.com/debtcollective/parent/issues/153)
- [x] Add member head shots
- [x] Add colorized comic
- [ ] ~~Write up guide for organizers to reference when creating new posts~~ (https://github.com/debtcollective/parent/issues/154)
- [ ] ~~Update the links in the header & footer to point to the right places across our services~~ (https://github.com/debtcollective/parent/issues/155)
- [ ] ~~Deploy the media site to S3 w/ cloudfront~~ (https://github.com/debtcollective/parent/issues/156)
- [x] Add new art to the art section
- [ ] ~~Buttons below The Power Report don’t work yet~~ (Fairly certain this is a bug with siteleaf's preview functionality as those buttons are fine when you build the site normally)
- [x] Remove “The Latest From” text above Power Report
- [ ] Fix video stretching on profiles main page

**Comment by annlarson** [comment]
Hi, this is looking great (in siteleaf). Here are some things Laura and I noted. Many of them you may already be aware of.  Thanks.


replace comic with color version
add new art to the art section
buttons below The Power Report don’t work yet
remove “The Latest From” text above Power Report
video is stretched in our view for some reason

Laura will send interview material for art work asap
special reports need to go in opposite order, so the latest is first. In fact we have a new post that can be the latest special report, replacing the previous post about court cases: http://blog.debtcollective.org/courtsupdate2/ 
There are a lot of errors for the pages generating in general on our end

**Comment by marcondag** [comment]
The last thing for this particular issue is going to be finishing the profiles big feed. Everything else has an individual issue that can be used to track those tasks.
