### ISSUE TITLE
Implement Donation Modal as embeddable library, based on Stripe Elements

### ISSUE THREAD

**Issue by saramarcondes** [debtcollective/parent#161]
Currently, we have donations implemented using the Stripe API in the Dispute tools app. We need to be able to donate from any application, so we need to build this as an integration that doesn't have dependencies except for the [Stripe Elements](https://stripe.com/docs/stripe-js) library.

Here's how it looks, it integrates the [PaymentRequest API](https://developers.google.com/web/fundamentals/payments/), which give us Apple Pay, Microsoft Pay and Google Pay OTB.

![image](https://user-images.githubusercontent.com/849872/44998590-7a739200-af7c-11e8-9eab-63fb94cf37af.png)

## Notes

We may want to explore Serverless to implement this, it will be cheaper and a lot easier to maintain.

Here's an article talking about it https://yos.io/2017/06/22/serverless-stripe/

## Tasks

- [ ] Research and spec out the implementation of the library
- [ ] Research what payment options we have (one-time, subscriptions)
- [ ] Develop a library or a set of files we can integrate easily to add donations in all of our websites

## Acceptance Criteria

- User and guests should be able to donate using the library
- Developers should be able to integrate this without installing additional dependencies

**Comment by marcondag** [comment]
Ah that does sort of throw a wrench in things... Though I think the header could just define a window function to open the modal and the footers could call it... Or else the header repo could also export a Vue component for the footer. But the first option is faster.

**Comment by marcondag** [comment]
This strategy is under review. There's a lot of churn to get the donation modal into the header and also be openable from the footer.

Might be better to change the current donation workflow that exists in the tools into a page and just link to the page.

**Comment by orlando** [comment]
Updating the title, we shouldn't include this into the header. Not sure how hard is to do this using the Stripe SDK, the idea is to trigger the Stripe form specifying a minimum amount users can donate.

**Comment by marcondag** [comment]
This needs to be revisited and should get a quick spec.

The most straightforward approach would be to simply turn the current donation page into a static page in the dispute-tools and just link there whenever a member what's to make a donation.

We should also start storing references to the donations (especially the recurring donations) in the database so that we can later on implement a way for members to cancel recurring donations without having to email us.

Given the state of the current code, it would probably be easier to re-implement a simple Stripe Elements component on a new page. The backend code lacks any unit tests and is, in general, pretty disorganized.

Moving back to the backlog until @orlan

**Comment by orlando** [comment]
I'll change the description of this ticket, it would be a lot easier to do the integration directly with stripe instead of managing this code ourselves.

**Comment by orlando** [comment]
Let's research on how to integrate Stripe Elements, I would like to keep this as a front-end integration only so we embed this easily in other apps. If this approach is not possible, let's discuss approaches when preparing the spec
