### ISSUE TITLE
Persist user data in the Dispute database

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#191]
Right now we are querying user data for each user we have in the admin view. Querying user data has disadvantages to having the data in the same database. 

This ticket supersedes #10 

## Tasks

- [ ] Create necessary fields in the User table
- [ ] Update user information with SSO data on every login
- [ ] Change how we display user information in the admin side to use the local user data.

## Acceptance criteria

- Reduce the amount of requests we make to the Discourse API
- Make user data available in all places where's needed in the admin

**Comment by orlando** [comment]
Moving **Make user data available in all places where's needed in the admin** into it's own ticket https://github.com/debtcollective/parent/issues/213
