### ISSUE TITLE
Remove the reply comment box in the Dispute show view

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#203]
Since we are moving user communication to Discourse, we need to remove the comment box in the Dispute show view and replace it with a link to the Discourse private message corresponding to this Dispute (implemented in #194)

![image](https://user-images.githubusercontent.com/849872/45003115-8115ff80-afa4-11e8-8f1f-3cd482cd7ed3.png)

## Tasks

- [ ] Remove the comment box and the code related to it
- [ ] Change **Got a Reply?** to **Got a question?**
- [ ] Add a link to the Dispute's private message in Discourse with **Click here to communicate directly with the organizers about this dispute.** as text below **Got a question?**

## Acceptance criteria

- Redirect the user to Discourse if they want to communicate with admins
- The code for user comments in the Dispute tools app is removed

**Comment by marcondag** [comment]
What do we put here if there is no thread yet?

**Comment by orlando** [comment]
@marcondag updating this, we will create the PM afte the user starts the dispute filling

**Comment by marcondag** [comment]
What would y'all like the button/link to say? @annlarson @dawn3296

Something along the lines of:

> *Click here* to communicate directly with the organizers about this dispute?

**Comment by orlando** [comment]
@marcondag I think that works, I'll put that in the ticket description

**Comment by orlando** [comment]
About the layout

![image](https://user-images.githubusercontent.com/849872/45659914-463fbb80-babc-11e8-9504-4d14de04e216.png)

1. Let's remove the image and align the text with the rest
2. Keep the *Got a reply?* title and put the text below as a link

**Comment by marcondag** [comment]
I don’t think “got a reply” makes sense though because it doesn’t actually show the conversation, right? Should it be more like “Got a question?” Or “Need to get in touch with your organizer?”

**Comment by orlando** [comment]
Got a question sounds good 👍
