### ISSUE TITLE
Remove comment feature in "Dispute edit status" view in the tools' back office

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#204]
In order to improve the user messaging flow, we will make some changes in the **Dispute edit status** view.

![image](https://user-images.githubusercontent.com/849872/45003506-f7b4fc00-afa8-11e8-937b-bde43afd6760.png)

The idea is to keep admin communication inside the Back office, and move all the communication with the user to Discourse.

## Tasks

- [x] Remove the comment box and the code related to it
- [x] Remove the **Notify user checkbox** and the code related to it
- [x] Add a link that opens in a new tab to the Dispute unique PM in Discourse

## Acceptance criteria

- Comments UI was replaced with link to a Discourse PM
- Admin notes and the rest of the functionality works

**Comment by orlando** [comment]
After checking with @dawn3296, we want to keep this functionality, with #205 and #198 is enough.

Closing
