### ISSUE TITLE
Display all messages in the Discourse PM related to a Dispute in the "Dispute edit status" view in the tools backoffice

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#205]
Since we are moving the Dispute user communication to Discourse, we need a way to quickly see the messages in Discourse from the back office.

We currently have this view with a list of messages

![image](https://user-images.githubusercontent.com/849872/45003708-da812d00-afaa-11e8-8f6d-b28162759e4b.png)

The idea is to list both the comments in the Discourse PM and the admin notes in chronological order.

Also, while working on this, is a good time to display the actual admin name when creating notes instead of **The Debt Collective**

![image](https://user-images.githubusercontent.com/849872/45003788-993d4d00-afab-11e8-8c3f-0d1148388016.png)

## Tasks

- [ ] Research implementation and create a spec
- [ ] Fetch comments from Discourse's PM and display them in order
- [ ] Display admin notes and comments in chronological order.
- [ ] Admin notes should have the author name instead of **The Debt Collective**
- [ ] Make the modal wider to fit Discourse comments.

## Acceptance criteria

- Comments from Discourse are shown in the back office, along with admin notes, in chronological order.
- Admin notes have the actual author name instead of **The Debt Collective**

**Comment by orlando** [comment]
Yeah this is not a blocker for the Release, and this can work by asking the admins to go to the Discourse message for now. I'll move it to low priority for now

**Comment by orlando** [comment]
@marcondag yeah 3 sounds good, but we will need to have control on how we render the messages. We need to display all messages (including admin notes from the tools) chronologically, so the approach we should take is 2. Something like:

1. Pull all the messages from the Dispute PM. I'm not expecting this to become a performance issue due to the number of messages we may have.
2. Combine these messages with the admin notes for the Dispute. This can be done in the backend and just return JSON/HTML.
3. Display the messages in the edit status modal.

To reply to a message, admins need to go to Discourse, implementing this with all the features in the tools will be hard (attachments, markdown, mentions etc etc etc). We may take you to a specific message in Discourse if you click on top of it in the tools, but no more than that.

**Comment by marcondag** [comment]
Okay, that sounds good. I think we actually wouldn't be able to do 1 or 3 anyway because only admins assigned to the dispute (either via a group they are in or directly) would be able to see the PM. If we pull the messages from the back-end that will not be a problem.

But that brings up another question, currently if you're just a `dispute_pro` and you go to a dispute in the backoffice that you're not assigned to a click the "Open Discourse Thread" button, you'll be denied access to the PM, right? I can't test it right now but it just dawned on me, if you could check that. We should let the organizers know. The workaround is just that you'd have to assign yourself to the dispute causing you to get added to the thread in Discourse.

Option 2 at least makes it possible for any admin to read the thread for a dispute, but the problem of being able to reply will still exist.

Given that it doesn't need to be interactive or reactive, returning the rendered HTML from that endpoint with an ajax request makes sense, might be the fastest approach instead of using Vue & the cost it will inevitably incur.

**Comment by orlando** [comment]
@marcondag cool I'll check. If non assigned admins can't see the PM in Discourse then I think it's fine, is a way to enforce that only people related to the dispute is able to message the user.

**Comment by orlando** [comment]
Closing this as we are leaving the current dispute-tools repo in maintenance mode
