### ISSUE TITLE
Donation flow modal should open using a querystring

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#209]
We have a donation modal that lives inside the Dispute Tools app

[![http://recordit.co/sdAI0gbFtq](http://recordit.co/sdAI0gbFtq.gif)](http://recordit.co/sdAI0gbFtq)

We want to allow users from others sites to donate using this modal. To allow this, we need to do the following changes

## Tasks

- [ ] Allow modal to be opened by passing a `?donate` query parameter
- [ ] `Donate` link in the footer should
  - [ ] Open the donate modal if the user is inside the Dispute tools app
  - [ ] Open a new tab to the dispute tools app with the `?donate` query parameter.

## Acceptance criteria

- Users and guests are able to donate using the Donate link in the Dispute tools app
- Users and guests are redirected from other apps to the Dispute tools app when clicking on the **Donate** link.
