### ISSUE TITLE
Events/Actions

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#21]
In gitlab by @marcondag on Feb 19, 2018, 15:45

As a TDC member I want to be able to plan events and actions for other members to participate in so that we can change the world

## Tasks

- [ ] Install [`events-plugin-calendar`](https://meta.discourse.org/t/events-plugin-calendar/69776) into discourse
- [ ] Extend plugin to change the "bookmark"ing of an event to be "RSVP"
    - [ ] Extend plugin to change the "bookmark"ing of an action to be "I'm doing this"?
- [ ] Implement guided event creation page
    - [ ] When an admin is creating an event they are forced to provide a slug https://gitlab.com/debtcollective/debtcollective/issues/325
        - [ ] a slug is automatically suggested and filled in based on the name of the event (and location/month?)
        - [ ] the slug should be verified as unique without having to submit the form
    - [ ] Allow for distinction between "action" and "event"
        * (events are inward facing, actions are outward facing)
- [ ] Add an event and action category per collective
    * Events and Actions are sub-categories of the collective categories
    - [ ] Add topic templates for events and actions (? To discuss)
- [ ] Migrate existing events (?)

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 15:50

mentioned in issue #21

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 11:05

changed the description
