### ISSUE TITLE
Create a Discourse group for donators

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#229]
We don't a way to show in the Discourse forum which members have donated, this is something that should be visible to others members of the community. We may create a badge also and award it after every donation.

The approach will be after a user makes a donation, we check if it has an account and we add it to the group, then we can automatically award a badge based on a group https://meta.discourse.org/t/automatically-grant-a-badge-for-all-members-of-a-group/18147

## Tasks

- [ ] Research
- [ ] Put together a spec where you detail your approach
- [ ] Implement a trigger in donations to add a user to a group in Discourse
- [ ] Implement automatically awarding a badge to the `donators` group. Group name needs to be a variable.

## Acceptance criteria

- After a user donates and it has an account with us, add it to the `donators` group
