### ISSUE TITLE
Events/Actions

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#23]
In gitlab by @marcondag on Feb 19, 2018, 15:45

As a TDC member I want to be able to plan event and actions for other members to participate in so that we can change the world

## Tasks

- [x] Install [`events-plugin-calendar`](https://meta.discourse.org/t/events-plugin-calendar/69776) into discourse
  - [x] update terraform with settings
- [x] ~customize bookmark copy https://github.com/debtcollective/parent/issues/127~
- [x] guided event creation page https://github.com/debtcollective/parent/issues/128
- [x] actions and event for each collective https://github.com/debtcollective/parent/issues/129
- [x] ~implement designs~ deprioritized
- [x] ~Migrate existing events~

**Comment by shoshber** [comment]
I'm renaming "Events" (inward facing) to "Meetups" unless anyone objects

**Comment by shoshber** [comment]
@zakgreene @stephenkistner Some UX/design work would be helpful here.

**Comment by shoshber** [comment]
Actually, from what I remember, we agreed to rename "Events" to "Meetups" because their conception of "events" was for internal planning/organization, within the collectives. It would not include stuff like protests. Protests are actions. But most people would consider a protest to be an event, so it's a very confusing word to use. @annlarson do you remember what came out of our discussion here?

**Comment by shoshber** [comment]
We discussed it offline & decided on "events"
