### ISSUE TITLE
Upgrade Sentry to use new library and integrate front-end

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#230]
Raven library was deprecated in favor or [Sentry](https://docs.sentry.io/quickstart?platform=node). We need to update and change our code to use this new library.

It also has new features, that allow us to pass the environment we are currently running, so we don't have to create multiple projects in Sentry to get different DSN per environment.

## Tasks

- [x] Install [Sentry](https://docs.sentry.io/quickstart?platform=node).
- [x] Remove Raven from the tools app
- [x] Change our middlewares and our Raven wrapper (`/lib/raven.js`) to use the new Sentry lib

## Acceptance criteria

- Error reporting with Sentry should work with the new library.
- Error reporting in front-end works
