### ISSUE TITLE
Migrate wiki.debtcollective.org to AWS

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#233]
Right now the wiki is running in a digital ocean instead, we want to have all of our insfrastructure consolidated in one AWS account, so we need to migrate this service to AWS too.

## Tasks

- [ ] Deploy a mediawiki instance in AWS using Terraform
- [ ] Backup and Restore the data from `wiki.debtcollective.org` into the new AWS instance
- [ ] Point `wiki.debtcollective.org` to the new aws instance in Route 53 with Terraform
- [ ] Remove the mediawiki instance from Digital Ocean

## Acceptance criteria

- Wiki is running in AWS with the same data as Digital Ocean
