### ISSUE TITLE
Remove tools landing page, redirect users directly to /dispute-tools instead.

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#234]
In the previous version, we hosted the tools at `debtcollective.org`, so it made sense the tools to have a landing page. Now we are hosting the tools at `tools.debtcollective.org` and the landing page at `debtcollective.org`. We can remove the code for the landing page in the tools and make `dispute-tools` the homepage. Or we can change the redirection to take users to `/dispute-tools` when they visit `tools.debtcollective.org`, any of the two solutions works, but I'll prefer to remove the code (less code is better)

## Tasks

- [ ] Research on the impact of removing the landing page code from the tools and make the current page `/dispute-tools` be available at `/`
- [ ] If above is too complex to implement, remove the landing page code and just redirect users to `/dispute-tools` if the visit `tools.debtcollective.org`

## Acceptance criteria

- [ ] Users don't see the old landing page at `tools.debtcollective.org`
