### ISSUE TITLE
Customize the account we use for the Dispute tools integration with Discourse

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#245]
Right now when we interact with Discourse using the API, every interaction comes from the `system` user. We want to change this user to something more friendly and specific for the Tools integration.

Here's for example how to make modifications to the `discobot` user https://meta.discourse.org/t/customize-discobot-user/63233/47. We can follow the same approach to customize this new user for us.

## Notes

Since we might have other integrations in the future, it might be a good idea to one account for each integration we need since [Discourse doesn't support multiple API keys for one account](https://meta.discourse.org/t/cant-generate-multiple-api-keys/21011/2).

**Also, we still need to define the profile information for this user before working on this ticket**

## Tasks

- [ ] Create a new user for the Dispute tools integration, this should be added to the `discourse-seed` repo
- [ ] Modify this user profile with a name, description and avatar.
- [ ] Create an API key that is going to be used by the tools integration.

## Acceptance criteria

- All the interactions from the Dispute tools app with Discourse should be made through the new dispute tools user.
