### ISSUE TITLE
Fixes for the Header

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#256]
The header looks broken in certain resolutions in the tools app, we want to fix this independent of 
the number of items we may have in the menu.

![image.png](https://images.zenhubusercontent.com/55c91a544f7a08fbb7f43521/8fbdce9e-62ed-4ade-835f-09dd3b19b6a2)

Also, we want to make it look more like the header from Discourse, so we have the same style across all our apps.

![image.png](https://images.zenhubusercontent.com/55c91a544f7a08fbb7f43521/7857e6f2-9b41-4b13-a51e-39d3e583d973)

## Notes
One approach for the responsive menu items is to move items to the **More** dropdown as the screen gets smaller, until we change it to mobile.

**from #188 (Mobile header menu button is a different size when open causing the header to jiggle when toggled between the two states)**

This should be fixed by making the hamburger menu icon smaller to match the size of the `X`. In any case, there should be no horizontal movement in the header when toggling between the two states (nor should the login button be cut off the side of the screen)

<img width="349" alt="screen shot 2018-08-21 at 2 16 18 pm" src="https://user-images.githubusercontent.com/24264157/44475662-7e9dc800-a5ea-11e8-9b81-101fce791eec.png">

<img width="366" alt="screen shot 2018-08-21 at 2 16 14 pm" src="https://user-images.githubusercontent.com/24264157/44475672-80678b80-a5ea-11e8-9fde-f698a2f6b2a0.png">

## Tasks

- [ ] Create a spec with the solution
- [ ] Implement the solution
- [ ] Test in different browsers and mobile devices

## Acceptance criteria

- The header is responsive and works in both desktop and mobile
- The header icons and avatar look more like the ones from the community
