### ISSUE TITLE
Move Dispute Tool description from the database to locale file

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#262]
Right now the description of a tool is stored in the database in the **DisputeTools** table, this makes it harder to change the information of the tools, and prevent us to translate the app in multiple languages easily.

We want to move all the information related to the tools to code, and integrate https://github.com/fnando/i18n-js to have strings in a locale file.

## Tasks

- [ ] Integrate https://github.com/fnando/i18n-js.
- [ ] Move Dispute Tools about to i18n-js.
- [ ] Remove **about** column from **DisputeTools** table.

## Acceptance criteria

- Dispute Tools description (**about** column) should be stored in code and not in the database

**Comment by orlando** [comment]
This will be implemented in the new tools release
