### ISSUE TITLE
Mediawiki SSO

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#6]
There's a tutorial that may work for us https://meta.discourse.org/t/using-discourse-sso-with-mediawiki/69218

## Tasks

- [ ] Use Discourse SSO to log into wiki
- [ ] User permissions should be stored in Discourse as user_group information
- [ ] User should be redirected to the wiki page they were trying to access after authenticating with SSO
