### ISSUE TITLE
Members should be able to view their profile information

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#67]
In gitlab by @marcondag on Feb 19, 2018, 15:16

As a debt collective member I want to be able to view my profile information so that I know what the debt collective already knows about me

## Tasks

- [ ] Display user information including extended user fields
- [ ] Only logged in members are able to see other members profile's
- [ ] old URL does not show 404

## Assumptions

1. There is a UI mockup for displaying the user information
