### ISSUE TITLE
Mediawiki SSO

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#8]
In gitlab by @marcondag on Feb 19, 2018, 14:34

## Tasks

- [ ] Use Discourse SSO to log into wiki
- [ ] User permissions should be stored in Discourse as user_group information
- [ ] User should be redirected to the wiki page they were trying to access after authenticating with SSO

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 14:35

added ~3521978 label

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 16:11

changed the description

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 21, 2018, 17:06

changed the description
